version: '3'
services:
    scribble-client:
        build: ./client
        container_name: scribble-client
        restart: unless-stopped
        volumes:
            - ./client:/app
            - ./client/node_modules:/app/node_modules
        environment:
            - HOST=0.0.0.0
            - NODE_ENV=development

    scribble-server:
        build: ./server
        container_name: scribble-server
        volumes:
            - ./server:/app
        environment:
            - DEBUG=1

    scribble-router:
        image: nginx:latest
        container_name: scribble-router
        volumes:
            - ./nginx/default.conf:/etc/nginx/conf.d/default.conf
        ports:
            - "80:80"
            - "443:443"
        command: "nginx -g 'daemon off;'"

    scribble-database:
        image: mysql:latest
        container_name: scribble-database
        command: --default-authentication-plugin=mysql_native_password
        restart: unless-stopped
        ports:
            - "3306:3306"
        volumes:
            - mysql-datavolume:/var/lib/msql
        environment:
            MYSQL_DATABASE: "db"
            MYSQL_USER: "user"
            MYSQL_ROOT_PASSWORD: "password"
            MYSQL_ROOT_PASSWORD: "password"

volumes:
    mysql-datavolume:
