version: '3'
services:
    scribble-client:
        build: ./client
        container_name: scribble-client
        restart: on-failure
        volumes:
            - scribble-client-static:/app
        environment:
            - NODE_ENV=production

    scribble-server:
        build: ./server
        container_name: scribble-server
        restart: always
        volumes:
            - ./server:/app

    scribble-router:
        image: nginx:latest
        container_name: scribble-router
        restart: always
        volumes:
            - ./nginx/prod.conf:/etc/nginx/conf.d/default.conf
            - scribble-client-static:/var/www/scribble:ro
        ports:
            - "${PORT:-80}:80"
            - "${HTTPS_PORT:-443}:443"
        command: "nginx -g 'daemon off;'"

    scribble-database:
        image: mongo:latest
        container_name: scribble-database
        volumes:
            - ./database_volume:/data/db
        restart: always
        environment:
            MONGO_INITDB_DATABASE: strapi

    scribble-strapi:
        build: ./strapi
        container_name: scribble-strapi
        volumes:
            - ./strapi:/usr/src/api
        restart: always
        depends_on:
            - scribble-database

volumes:
    scribble-client-static:
